version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/smpr"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "rust"

  - package-ecosystem: "cargo"
    directory: "/rabsody"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "rust"
      - "rabsody"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
